declare module "@citation-js/core"
declare module "@citation-js/date"
declare module "@citation-js/name"
declare module "@citation-js/plugin-csl"
declare module "ckeditor5-custom-build/build/ckeditor"
