name: Github Pages Deploy

on:
  push:
    branches:
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.16.1]

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install and build
        run: yarn install && yarn run build

      - name: Test
        run: yarn run test

      - name: Build
        run: yarn run build

      - name: Deploy
        env:
          MY_EMAIL: ahmadsos5009@hotmail.com
          MY_NAME: asouqi
        run: |
          git config --global user.email $MY_EMAIL
          git config --global user.name $MY_NAME
          yarn install
          yarn deploy
