export const labels = {
  title: "Title",
  accessed: "Accessed",
  URL: "URL",
  abstract: "Abstract",
  publisher: "Publisher",
  issued: "Date",
  language: "Language",
  shortTitle: "Short Title",
  archive: "Archive",
  archive_location: "Loc. in Archive",
  source: "Library Catalog",
  "call-number": "Call Number",
  note: "Annotation",
  "container-title": "Reporter",
  volume: "Volume",
  issue: "Priority Numbers",
  page: "Pages",
  ISSN: "ISSN",
  "publisher-place": "Place",
  edition: "Edition",
  section: "Section",
  "collection-title": "Series Title",
  journalAbbreviation: "Journal Abbr",
  DOI: "DOI",
  authority: "Issuing Authority",
  "chapter-number": "Session",
  references: "References",
  "collection-number": "Series Number",
  "number-of-volumes": "# of Volumes",
  "number-of-pages": "# of Pages",
  ISBN: "ISBN",
  dimensions: "Artwork Size",
  scale: "Scale",
  event: "Meeting Name",
  submitted: "Filing Date",
  status: "Legal Status",
}
export const descriptions = {
  title: "primary title of the item",
  accessed: "date the item has been accessed",
  URL: "Uniform Resource Locator (e.g. “http://aem.asm.org/cgi/content/full/74/9/2766”)",
  abstract: "abstract of the item (e.g. the abstract of a journal article)",
  publisher: "publisher",
  issued: "date the item was issued/published",
  language: "Language code. Not intended for display purposes.",
  shortTitle: "",
  archive: "archive storing the item",
  archive_location:
    "storage location within an archive (e.g. a box and folder number)",
  source: "from whence the item originates (e.g. a library catalog or database)",
  "call-number": "call number (to locate the item in a library)",
  note: "Descriptive text or notes about an item (e.g. in an annotated bibliography)",
  "container-title":
    "title of the container holding the item (e.g. the book title for a book chapter, the journal title for a journal article)",
  volume:
    "(container) volume holding the item (e.g. “2” when citing a chapter from book volume 2)",
  issue:
    "(container) issue holding the item (e.g. “5” when citing a journal article from journal volume 2, issue 5)",
  page: "range of pages the item (e.g. a journal article) covers in a container (e.g. a journal issue)",
  ISSN: "International Standard Serial Number",
  "publisher-place": "geographic location of the publisher",
  edition:
    "(container) edition holding the item (e.g. “3” when citing a chapter in the third edition of a book)",
  section:
    "container section holding the item (e.g. “politics” for a newspaper article)",
  "collection-title":
    "title of the collection holding the item (e.g. the series title for a book)",
  journalAbbreviation: "",
  DOI: "Digital Object Identifier (e.g. “10.1128/AEM.02591-07”)",
  authority:
    "issuing or judicial authority (e.g. “USPTO” for a patent, “Fairfax Circuit Court” for a legal case)",
  "chapter-number": "chapter number",
  references: "resources related to the procedural history of a legal case",
  "collection-number":
    "number identifying the collection holding the item (e.g. the series number for a book)",
  "number-of-volumes":
    "total number of volumes, usable for citing multi-volume books and such",
  "number-of-pages": "total number of pages of the cited item",
  ISBN: "International Standard Book Number",
  dimensions:
    "physical (e.g. size) or temporal (e.g. running time) dimensions of the item",
  scale: "scale of e.g. a map",
  event:
    "name of the related event (e.g. the conference name when citing a conference paper)",
  submitted: "date the item (e.g. a manuscript) has been submitted for publication",
  status: "(publication) status of the item (e.g. “forthcoming”)",
}
export const users = {
  author: "author",
  editor: "editor",
  "container-author": "bookAuthor",
  composer: "composer",
  director: "director",
  interviewer: "interviewer",
  recipient: "recipient",
  "reviewed-author": "reviewedAuthor",
  "collection-editor": "seriesEditor",
  translator: "translator",
  contributor: "contributor",
}
export const documentUser = {
  article: ["author", "contributor", "editor", "reviewed-author", "translator"],
  "article-magazine": ["author", "contributor", "reviewed-author", "translator"],
  "article-newspaper": ["author", "contributor", "reviewed-author", "translator"],
  "article-journal": [
    "author",
    "contributor",
    "editor",
    "reviewed-author",
    "translator",
  ],
  bill: ["contributor"],
  book: ["author", "contributor", "editor", "collection-editor", "translator"],
  chapter: [
    "author",
    "container-author",
    "contributor",
    "editor",
    "collection-editor",
    "translator",
  ],
  "entry-dictionary": [
    "author",
    "contributor",
    "editor",
    "collection-editor",
    "translator",
  ],
  "entry-encyclopedia": [
    "author",
    "contributor",
    "editor",
    "collection-editor",
    "translator",
  ],
  graphic: ["contributor"],
  legislation: ["author", "contributor"],
  legal_case: ["author", "contributor"],
  manuscript: ["author", "contributor", "translator"],
  map: ["contributor", "collection-editor"],
  "paper-conference": [
    "author",
    "contributor",
    "editor",
    "collection-editor",
    "translator",
  ],
  patent: ["contributor"],
  post: ["author", "contributor"],
  "post-weblog": ["author", "contributor"],
  personal_communication: ["author", "contributor", "recipient"],
  report: ["author", "contributor", "collection-editor", "translator"],
  speech: ["contributor"],
  thesis: ["author", "contributor"],
  webpage: ["author", "contributor", "translator"],
}
export const documentFields = {
  article: [
    "title",
    "accessed",
    "URL",
    "abstract",
    "publisher",
    "issued",
    "language",
    "shortTitle",
    "archive",
    "archive_location",
    "source",
    "call-number",
    "note",
  ],
  "article-magazine": [
    "title",
    "abstract",
    "container-title",
    "volume",
    "issue",
    "issued",
    "page",
    "language",
    "ISSN",
    "shortTitle",
    "URL",
    "accessed",
    "archive",
    "archive_location",
    "source",
    "call-number",
    "note",
  ],
  "article-newspaper": [
    "title",
    "abstract",
    "container-title",
    "publisher-place",
    "edition",
    "issued",
    "section",
    "page",
    "language",
    "shortTitle",
    "ISSN",
    "URL",
    "accessed",
    "archive",
    "archive_location",
    "source",
    "call-number",
    "note",
  ],
  "article-journal": [
    "title",
    "abstract",
    "container-title",
    "volume",
    "issue",
    "page",
    "issued",
    "collection-title",
    "journalAbbreviation",
    "language",
    "DOI",
    "ISSN",
    "shortTitle",
    "URL",
    "accessed",
    "archive",
    "archive_location",
    "source",
    "call-number",
    "note",
  ],
  bill: [
    "title",
    "abstract",
    "container-title",
    "section",
    "authority",
    "chapter-number",
    "references",
    "issued",
    "language",
    "URL",
    "accessed",
    "shortTitle",
    "note",
  ],
  book: [
    "title",
    "abstract",
    "collection-title",
    "collection-number",
    "volume",
    "number-of-volumes",
    "edition",
    "publisher-place",
    "issued",
    "number-of-pages",
    "language",
    "ISBN",
    "shortTitle",
    "URL",
    "accessed",
    "archive",
    "archive_location",
    "source",
    "call-number",
    "note",
  ],
  chapter: [
    "title",
    "abstract",
    "collection-title",
    "collection-number",
    "volume",
    "number-of-volumes",
    "edition",
    "publisher-place",
    "issued",
    "page",
    "language",
    "ISBN",
    "shortTitle",
    "URL",
    "accessed",
    "archive",
    "archive_location",
    "source",
    "call-number",
    "note",
  ],
  "entry-dictionary": [
    "title",
    "abstract",
    "collection-title",
    "collection-number",
    "volume",
    "number-of-volumes",
    "edition",
    "publisher-place",
    "issued",
    "page",
    "language",
    "ISBN",
    "shortTitle",
    "URL",
    "accessed",
    "archive",
    "archive_location",
    "source",
    "call-number",
    "note",
  ],
  "entry-encyclopedia": [
    "title",
    "abstract",
    "collection-title",
    "collection-number",
    "volume",
    "number-of-volumes",
    "edition",
    "publisher-place",
    "issued",
    "page",
    "ISBN",
    "shortTitle",
    "URL",
    "accessed",
    "language",
    "archive",
    "archive_location",
    "source",
    "call-number",
    "note",
  ],
  graphic: [
    "title",
    "abstract",
    "dimensions",
    "issued",
    "language",
    "shortTitle",
    "archive",
    "archive_location",
    "source",
    "call-number",
    "URL",
    "accessed",
    "note",
  ],
  legislation: [
    "abstract",
    "container-title",
    "volume",
    "page",
    "section",
    "chapter-number",
    "references",
    "language",
    "shortTitle",
    "URL",
    "accessed",
    "note",
  ],
  legal_case: [
    "abstract",
    "container-title",
    "authority",
    "references",
    "language",
    "shortTitle",
    "URL",
    "accessed",
    "note",
  ],
  manuscript: [
    "title",
    "abstract",
    "publisher-place",
    "issued",
    "number-of-pages",
    "language",
    "shortTitle",
    "URL",
    "accessed",
    "archive",
    "archive_location",
    "source",
    "call-number",
    "note",
  ],
  map: [
    "title",
    "abstract",
    "scale",
    "collection-title",
    "edition",
    "publisher-place",
    "issued",
    "language",
    "ISBN",
    "shortTitle",
    "URL",
    "accessed",
    "archive",
    "archive_location",
    "source",
    "call-number",
    "note",
  ],
  "paper-conference": [
    "title",
    "abstract",
    "issued",
    "event",
    "publisher-place",
    "volume",
    "page",
    "collection-title",
    "language",
    "DOI",
    "ISBN",
    "shortTitle",
    "URL",
    "accessed",
    "archive",
    "archive_location",
    "source",
    "call-number",
    "note",
  ],
  patent: [
    "title",
    "abstract",
    "publisher-place",
    "authority",
    "submitted",
    "page",
    "call-number",
    "issue",
    "references",
    "status",
    "language",
    "shortTitle",
    "URL",
    "accessed",
    "note",
  ],
  post: [
    "title",
    "abstract",
    "issued",
    "language",
    "shortTitle",
    "URL",
    "accessed",
    "note",
  ],
  "post-weblog": [
    "title",
    "abstract",
    "issued",
    "URL",
    "accessed",
    "language",
    "shortTitle",
    "note",
  ],
  personal_communication: [
    "title",
    "abstract",
    "issued",
    "language",
    "shortTitle",
    "URL",
    "accessed",
    "archive",
    "archive_location",
    "source",
    "call-number",
    "note",
  ],
  report: [
    "title",
    "abstract",
    "collection-title",
    "publisher-place",
    "issued",
    "page",
    "language",
    "shortTitle",
    "URL",
    "accessed",
    "archive",
    "archive_location",
    "source",
    "call-number",
    "note",
  ],
  speech: [
    "title",
    "abstract",
    "issued",
    "publisher-place",
    "event",
    "URL",
    "accessed",
    "language",
    "shortTitle",
    "note",
  ],
  thesis: [
    "title",
    "abstract",
    "publisher-place",
    "issued",
    "number-of-pages",
    "language",
    "shortTitle",
    "URL",
    "accessed",
    "archive",
    "archive_location",
    "source",
    "call-number",
    "note",
  ],
  webpage: [
    "title",
    "abstract",
    "issued",
    "shortTitle",
    "URL",
    "accessed",
    "language",
    "note",
  ],
}
